fragment OutcomeDetails on GameOutcome {
  id
  name
  text
  sortOrder
  promptOptionsFilter {
    results {
      ... on PromptOption {
        id
        value
      }
    }
  }
}

query GetOutcomeByAnswersQuery($answers: [ID!]!) {
  allGameOutcome(where: { promptOptionsFilter: { gameOutcome_ids: $answers } }) {
    results {
      ...OutcomeDetails
    }
  }
}
