fragment OutcomeDetails on GameOutcome {
  id
  name
  themes {
    results {
      ... on GameTheme {
        id
        name
      }
    }
  }
  title
  productsIntro
  outcomeReasons {
    results {
      ... on GameOutcomeReason {
        product
        reason
      }
    }
  }
  videoTitle
  videoIntro
  videoid
  guidesIntro
  xcFeaturesTitle
  xcFeaturesIntro
  xpFeaturesTitle
  xpFeaturesIntro
  xmFeaturesTitle
  xmFeaturesIntro
  aspnetHeadlessTitle
  aspnetHeadlessIntro
}

query GetOutcomeByThemeIdQuery($id: ID!) {
  allGameOutcome(where: { themes: { gameOutcome_ids: $id } }) {
    results {
      ...OutcomeDetails
    }
  }
}

query GetOutcomeByIdQuery($id: String!) {
  gameOutcome(id: $id) {
    ...OutcomeDetails
  }
}
