fragment PersonaFragment on Persona {
  id
  name
  personaImage {
    results {
      id
      fileUrl
      fileName
    }
  }
  theme {
    results {
      ... on Theme {
        id
        name
      }
    }
  }
}

query GetAllPersonasQuery {
  allPersona {
    results {
      ...PersonaFragment
    }
  }
}

query GetPersonaByIdQuery($id: String!) {
  persona(id: $id) {
    ...PersonaFragment
  }
}

query GetPersonasByThemeIdQuery($id: ID!) {
  allPersona(where: { theme: { persona_ids: $id } }) {
    results {
      ...PersonaFragment
    }
  }
}
