fragment PromptDetails on Prompt {
  id
  name
  questionId
  question
  bodyText
  theme {
    results {
      __typename
      ... on Theme {
        id
      }
    }
  }
  nextPrompts {
    results {
      ... on Prompt {
        id
      }
    }
  }
  persona {
    results {
      ... on Persona {
        id
      }
    }
  }
  optionType {
    results {
      ... on PromptOptionType {
        id
        name
      }
    }
  }
  disabled
  start
  background {
    results {
      id
      fileUrl
      fileName
    }
  }
  options(first: 25) {
    results {
      ... on PromptOption {
        id
        name
        label
        value
        tooltip
        nextPrompts {
          results {
            ... on Prompt {
              id
            }
          }
        }
      }
    }
  }
}

query GetAllPromptsQuery {
  allPrompt {
    results {
      ...PromptDetails
    }
  }
}

query GetPromptsByPersonaQuery($personaId: ID!) {
  allPrompt(
    first: 1000
    where: { persona: { prompt_ids: $personaId } } ) {
    results {
      ...PromptDetails
    }
  }
}

query GetPromptsByThemeQuery($themeId: ID!) {
  allPrompt(where: { theme: { prompt_ids: $themeId } }) {
    results {
      ...PromptDetails
    }
  }
}
