fragment ThemeFragment on Theme {
  id
  name
  description
  chakraTheme
  startButtonText
  disabled
  image {
    results {
      id
      fileUrl
      fileName
    }
  }
  avatarGallery(first: 25) {
    results {
      id
      fileUrl
      fileName
    }
  }
}

query GetAllThemesQuery {
  allTheme {
    results {
      ...ThemeFragment
    }
  }
}

query GetThemesByIdQuery($id: String!) {
  theme(id: $id) {
    ...ThemeFragment
  }
}
