fragment Theme on GameTheme {
  id
  name
  description
  characterImage {
    results {
      id
      fileUrl
      fileName
    }
  }
  avatarGallery {
    results {
      id
      fileUrl
      fileName
    }
  }
}

query GetAllThemesQuery {
  allGameTheme {
    results {
      ...Theme
    }
  }
}

query GetThemesByIdQuery($id: String!) {
  gameTheme(id: $id) {
    ...Theme
  }
}
